### ISSUE TITLE
`ranger` as a faster alternative to `randomForests`

### ISSUE THREAD

**Issue by KhatriVivek** [amices/mice#264] opened 2020-09-09 21:51 UTC
For MICE Random Forests, have you thought about replacing the "randomForests" package with "ranger"?

The creators of the "ranger" package show that they get similar results to "randomForest", but "ranger" is much faster. This is the paper 
https://arxiv.org/pdf/1508.04409.pdf

Take care.

Vivek

**Comment by stefvanbuuren** [comment] 2020-09-10 07:32
Thanks for the suggestion. I wasn't aware of `ranger` and quickly scanned the paper. 

The `ranger` package seems a good alternative to `randomForest`. I have seen that package authors sometimes take shortcuts that compromise statistical validity in exchange for speed. I would be comfortable with implementing, offering and advocating `ranger` as an option if simulations as done in Doove et al (2014) show that the statistical validity is on par with `randomForest`. Any chance that you could make such calculations?

Doove, L. L., S. Van Buuren, and E. Dusseldorp. 2014. “Recursive Partitioning for Missing Data Imputation in the Presence of Interaction Effects.” Computational Statistics & Data Analysis 72: 92–104.

**Comment by prockenschaub** [comment] 2020-09-18 15:46
I can have a look at running a calculation in line with Doove et al (2014). Since all simulations for that paper were done in R, is there any chance that the code for simulation is still floating around somewhere? They aren't too hard to reproduce, but using the original code would limit any room for mistakes/misinterpretations.

**Comment by shangzhi-hong** [comment] 2020-09-20 01:59
The "mice.rf" function can be problematic by using the observations has the same prediction value as if they were under the same node of RF: the equality tests of floating points can be wrong

Offering an alternative to the RF-based imputation (implemented using ranger) [https://github.com/shangzhi-hong/RfEmpImp], and "rfnode.cond" is the counterpart to "mice.rf" by finding the candidates using the information from the RF models, not the predictions. 

Still working on the paper to be published.

**Comment by stefvanbuuren** [comment] 2020-09-21 06:52
@prockenschaub That would be great. I don't have the source. Will try to track it down.

**Comment by stefvanbuuren** [comment] 2020-09-21 07:00
@shangzhi-hong Thanks for your comment. 

I don't quite get what the problem in `mice.impute.rf()` could be. The function creates a tree and samples one observed value from all members of the same leaf as the imputation. It doesn't really "predict" the  leaf value. Could you explain a bit more?

**Comment by prockenschaub** [comment] 2020-11-23 16:31
@stefvanbuuren I finally had a chance to look properly at this (I got tripped up by some of the changes to R since the original simulation code was written in 2012/14). Here's  a qick summary of my findings:

1. I believe the current implementation of `mice.impute.rf` intends to find donors in the same node, but currently uses the predictions instead. See #288 for a detailed explanation. This could be what @shangzhi-hong referred to, and I submitted a small PR #289 to fix this issue. 

2. For now, I have run the simulations presented in Table 2 of Doove et al. (2014), which simulates continuos predictors and response variables under high interaction correlation (r = 1.0) and medium effect size (f^2 = 0.15). For this scenario, the results from `randomForest` and `ranger` are highly comparable to the published results and to each other. I can also run the other parameter combinations and categorical variables if this should be required. 

```r

# Reproduced values from Table 1 (Doove et al., 2014)

# PMM
#>               Bias Coverage CI width   fmi Lambda
#> (Intercept)  0.114    0.490    0.223 0.474  0.461
#> x1          -0.001    0.955    0.230 0.504  0.490
#> x2          -0.006    0.960    0.230 0.502  0.488
#> x3           0.003    0.945    0.233 0.511  0.497
#> x8          -0.004    0.955    0.200 0.514  0.500
#> x9           0.002    0.970    0.228 0.617  0.602
#> xint        -0.109    0.035    0.117 0.366  0.356

# randomForest
#>               Bias Coverage CI width   fmi Lambda
#> (Intercept)  0.061    0.815    0.212 0.362  0.352
#> x1          -0.038    0.930    0.213 0.374  0.364
#> x2          -0.038    0.915    0.214 0.376  0.365
#> x3          -0.003    0.980    0.218 0.396  0.385
#> x8          -0.061    0.735    0.183 0.371  0.361
#> x9          -0.085    0.620    0.192 0.427  0.415
#> xint        -0.064    0.500    0.127 0.403  0.392

# ranger 
#>               Bias Coverage CI width   fmi Lambda
#> (Intercept)  0.060    0.815    0.213 0.369  0.358
#> x1          -0.039    0.935    0.215 0.383  0.372
#> x2          -0.038    0.930    0.215 0.382  0.372
#> x3          -0.004    0.985    0.217 0.388  0.377
#> x8          -0.061    0.755    0.183 0.372  0.362
#> x9          -0.085    0.605    0.191 0.420  0.409
#> xint        -0.064    0.505    0.128 0.407  0.396

```

3. When looking at a dataset size of 1,000, my current implementation of `mice.impute.ranger` is roughly twice as fast as `mice.impute.rf.custom` (which I used instead of `mice.impute.rf` so I could already implement the fix in #289). In some further ad hoc benchmarks I performed, fitting of `ranger` was between 8-12 times faster than `randomForest` but a lot of the computing time in `mice.impute.ranger` is spent on matching the donors *after* model fitting, therefore exchanging `randomForest` for `ranger` does not speed up `mice.impute.ranger` quite as much as I had hoped. There might be scope to speed up this matching, but this would be independent of using `ranger` or `randomForest`.

```r
# Compare speed -----------------------------------------------------------

set.seed(1234)
B <- c(b0=0, b1=.31, b2=.31, b3=.31, b4=.31, b5=.31, b6=.28)
data <- replicate(
  5, 
  makeMARmid(createdata(n = 1000, B = B, interact = c(3, 3))), 
  simplify = FALSE
)

# PMM
microbenchmark(
  sapply(data, simplify = "array",
         run_and_eval_imputation, 
         m = 2, method="pmm", maxit = 1),
  times = 10L
)
#> Unit: milliseconds
#>                                                                                              expr
#>  sapply(data, simplify = "array", run_and_eval_imputation, m = 2,      method = "pmm", maxit = 1)
#>       min       lq     mean   median       uq      max neval
#>  299.6656 302.1356 317.3776 320.8415 332.0882 337.8891    10

# randomForest
microbenchmark(
  sapply(data, simplify = "array",
         run_and_eval_imputation, 
         m = 2, method="rf.custom", maxit = 1, ntree = 100),
  times = 10L
)
#> Unit: seconds
#>                                                                                                                 expr
#>  sapply(data, simplify = "array", run_and_eval_imputation, m = 2,      method = "rf.custom", maxit = 1, ntree = 100)
#>       min       lq     mean   median       uq      max neval
#>  3.156661 3.258607 3.411222 3.402734 3.547399 3.670707    10

# ranger (implementation using the same onetree function as randomForest)
# microbenchmark(
#   sapply(data, simplify = "array",
#          run_and_eval_imputation, 
#          m = 2, method="ranger.onetree", maxit = 1, ntree = 100),
#   times = 10L
# )

# ranger
microbenchmark(
  sapply(data, simplify = "array",
         run_and_eval_imputation, 
         m = 2, method="ranger", maxit = 1, ntree = 100),
  times = 10L
)
#> Unit: seconds
#>                                                                                                              expr
#>  sapply(data, simplify = "array", run_and_eval_imputation, m = 2,      method = "ranger", maxit = 1, ntree = 100)
#>       min       lq     mean   median       uq      max neval
#>  1.520069 1.550531 1.654298 1.592867 1.630518 2.253295    10
```

All code used to obtain the above numbers can be found [here](https://github.com/prockenschaub/Misc/blob/master/R/mice.ranger/mice_test_ranger.R).

**Comment by prockenschaub** [comment] 2021-04-07 07:25
@stefvanbuuren I can add `mice.impute.ranger()` this week. Alternatively, we could also integrate it into `mice.impute.rf` and add something like an `engine` parameter (with `randomForest` as the default engine for compatibility). This is inspired by how the `tidymodels` package deals with different implementaions of the same model class. Not sure if this is worth it but it would avoid blowing up the number of imputation methods if even faster implementations are released in the future. 

Regarding the `ranger.onetree()`, I personally can't think of a reason what it could be used for but am happy to include it if I missed some potential use case.

**Comment by stefvanbuuren** [comment] 2021-09-23 20:02
Now part of `mice`. Thanks for the help.

**Closed by stefvanbuuren** 2021-09-23 20:02 UTC
Labels: enhancement
