### ISSUE TITLE
error, mice not run

### ISSUE THREAD

**Issue by zhuoranw2021** [amices/mice#522] opened 2022-11-13 01:43 UTC
When running the mice() function, I got the error below:
Error in data.frame(it = s$it, im = s$im, dep = s$dep, meth = if (is.null(meth)) s$meth else meth, : 
arguments imply differing number of rows: 0, 1

**Comment by gerkovink** [comment] 2022-11-13 09:37
Can you provide a [reprex](https://reprex.tidyverse.org/)?

**Comment by stefvanbuuren** [comment] 2022-11-14 15:02
Closing. No reprex.

**Closed by stefvanbuuren** 2022-11-14 15:02 UTC

**Comment by gmhgmh-r** [comment] 2023-06-11 02:31
How did you solve this problem? Thank you

**Comment by stefvanbuuren** [comment] 2023-06-11 06:43
We did not because we cannot reproduce
