### ISSUE TITLE
the plot of standard deviation (SD) of variables in the iteration cruve after multiple imputation  are blank/empty

### ISSUE THREAD

**Issue by bengi000** [amices/mice#547] opened 2023-04-07 15:47 UTC
Hello!

I was running mice package to mulitply imputed a dataset with missing values in variables BP_HIGH and BP_LOW. But after I drew the imputed object RR_mice, the sd (Standard deviation) of them in iteration curve were empty as below:
![image](https://user-images.githubusercontent.com/89568671/230636943-e52e1bc3-c21a-4290-ba4e-b739c05e6806.png)
 
I had changed the predictors many times or even imputed with no other predictors, but the results were same. and i check the sd of each dataset was below :
> sd(result1$BP_HIGH)
[1] 21.07227
> sd(result2$BP_HIGH)
[1] 21.07519
> sd(result3$BP_HIGH)
[1] 21.07592
> sd(result4$BP_HIGH)
[1] 21.07555
> sd(result5$BP_HIGH)
[1] 21.07336

and I noticed that the number of missing in these two variables were both 1, is it countable for the issue, or what else could be?

**Comment by hanneoberman** [comment] 2023-04-07 21:44
Hi! This is expected behavior if there is only one imputed value for these variables. The plot shows the average and sd of the *imputed* values only. You could verify by looking at the `$chainMeans` and `$chainVariance` components of the `mids` object.

**Comment by hanneoberman** [comment] 2023-04-14 07:27
Closing the issue because of expected behaviour in `mice`. For more information see https://stefvanbuuren.name/fimd/sec-algoptions

**Closed by hanneoberman** 2023-04-14 07:27 UTC
