### ISSUE TITLE
as.mids changes values of data

### ISSUE THREAD

**Issue by mragusi** [amices/mice#327] opened 2021-03-26 11:51 UTC
Hi,

When converting data to a mids object (with the as.mids function) the values of the underlying data changes.

Scenario: I have imputed missing data using the `smcfcs` package which outputs a list of dataframes (for each imputation). I would like to convert this to a mids-object to use some of the excellent functions within the `mice` package. After imputation I also would like to apply mean-centering by cluster (site) of a variable. After conversion to a mids-object, the values of the mean-centered variable have changed (of only the data IDs that were non-missing in the original data). 

I have attached some sample data to reproduce the issue. I am using `mice_3.13.0`. 

First I assumed that it must be some error in my code, but I just can't figure out what.
The last possibility I could think of was that there was an issue with the as.mids function.

```
# Sample data
library(mice)
set.seed(123)
df <- data.frame(.id = rep(seq(1, 100, 1), 11), .imp = rep(0:10, rep(100, 11)), site = rep(sample(1:6, size = 100, replace = TRUE), 11), x1 = rep(rnorm(100, mean = 1, sd = 0.5), 11))
# Create NA
df[sample(1:100, size = 50, replace = FALSE), 'x1'] <- NA
# Original data
og <- df[df$.imp == 0,]
# Imputed data
imp <- df[df$.imp != 0,]
# Create list of dataframes (output of smcfcs); I guess not necessary for this sample data
imp<- split(imp, imp$.imp)

# Standardize by center x1 in original data
og$x1_stan <- as.vector(og$x1 - tapply(og$x1, og$site, mean, na.rm = TRUE)[og$site])

# Standardize by center x1 in imputed data and convert to long
long <- og
for (i in 1:10){
  temp <- imp[[i]]
  temp$x1_stan <- as.vector(temp$x1 - tapply(temp$x1, temp$site, mean)[temp$site])
  long <- rbind(long, temp)
  rm(temp, i)
}

# Check means in random imputed dataset
with(long[long$.imp==sample(1:10,1),], tapply(x1_stan, site, mean)) # Yes means are all zero

# Convert to mids
mids <- as.mids(long, .imp = '.imp', .id = '.id')
# Check means in random imputed dataset after conversion to mids
with(complete(mids, sample(1:10, 1)), tapply(x1_stan, site, mean)) # Means are not zero anymore???

### Plot values
i <- 3 # What imputation set
plot(long$x1_stan[long$.imp==i], complete(mids, i)$x1_stan) # Not a straight line
plot(long$x1[long$.imp==i], complete(mids, i)$x1) # Straight line
# With IDs with missing data
missing <- is.na(og$x1)
plot(long$x1_stan[long$.imp==i & missing], complete(mids, i)[missing,'x1_stan']) # Straight line
plot(long$x1[long$.imp==i & missing], complete(mids, i)[missing,]$x1) # Straight line
# And non-missing data
nonmissing <- !is.na(og$x1)
plot(long$x1_stan[long$.imp==i & nonmissing], complete(mids, i)[nonmissing, 'x1_stan']) # Not a straight line???
plot(long$x1[long$.imp==i & nonmissing], complete(mids, i)[nonmissing, 'x1']) # Straight line
```

**Comment by gerkovink** [comment] 2021-03-27 09:17
Thanks for your question. I have used your `df` to mimic a quick workflow to see if `as.mids()` performs as expected. In short; if I input your `df` into `as.mids()` and use `complete(action = "long")` on the resulting `mids` object, I end up with a data frame that is identical to your `df`. So `as.mids` is not flawed. 

``` r
library(mice)
library(dplyr)
library(magrittr)
set.seed(123)

# Sample data
df <- data.frame(.imp = rep(0:10, rep(100, 11)), 
                 .id = as.integer(rep(seq(1, 100, 1), 11)), 
                 site = rep(sample(1:6, size = 100, replace = TRUE), 11), 
                 x1 = rep(rnorm(100, mean = 1, sd = 0.5), 11))
# Create NA
df[sample(1:100, size = 50, replace = FALSE), 'x1'] <- NA
# impute
mids <- as.mids(df, .imp = 1)
long <- complete(mids, 
                 action = "long", 
                 include = TRUE)

#check if missings are propely imputed
all.equal(long$x1, df$x1)
#> [1] TRUE

#same long object after conversion?
identical(df, long)
#> [1] TRUE

# Original data
og <- df[df$.imp == 0,]
# Imputed data
imp <- df[df$.imp != 0,]
# Create list of dataframes (output of smcfcs); I guess not necessary for this sample data
imp<- split(imp, imp$.imp)

# Standardize by center x1 in original data
og$x1_stan <- as.vector(og$x1 - tapply(og$x1, og$site, mean, na.rm = TRUE)[og$site])

# Standardize by center x1 in imputed data and convert to long
long <- og
for (i in 1:10){
  temp <- imp[[i]]
  temp$x1_stan <- as.vector(temp$x1 - tapply(temp$x1, temp$site, mean)[temp$site])
  long <- rbind(long, temp)
  rm(temp, i)
}

# Issue
head(long)
#>   .imp .id site         x1     x1_stan
#> 1    0   1    3  1.0265021  0.07378463
#> 2    0   2    6         NA          NA
#> 3    0   3    3         NA          NA
#> 4    0   4    2  0.7544844 -0.06517642
#> 5    0   5    2 -0.1545844 -0.97424528
#> 6    0   6    6         NA          NA
long %>% filter(.imp == 1) %>% head()
#>   .imp .id site         x1      x1_stan
#> 1    1   1    3  1.0265021 -0.005040355
#> 2    1   2    6  1.4611337  0.352257386
#> 3    1   3    3  2.0250423  0.993499875
#> 4    1   4    2  0.7544844 -0.194811230
#> 5    1   5    2 -0.1545844 -1.103880085
#> 6    1   6    6  1.5028693  0.393992915
```

<sup>Created on 2021-03-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

The issue is that in your standardisation procedure, the bonafide observed data assumption is violated. Your *observed* standardised values are not identical across imputed sets --> which is a strict requirement. `as.mids()` takes the `.imp == 0` as its guide to determine which cells are observed - and constant across the `m` imputed sets - and which are not. Observations cannot differ across imputed sets.

**Comment by gerkovink** [comment] 2021-03-27 09:39
I believe that your standardisation procedure is flawed --> it is not proper to create standardised values over the imputations without considering the observations. In the for-loop this is not taken into consideration - and to be honest, I don't think that it should be considered. 

If I were you, I would pre-process after `as.mids`, but before analysis. Something like the below workflow.

``` r
library(mice)
library(dplyr)
library(magrittr)
library(purrr)
set.seed(123)

# Sample data
df <- data.frame(.imp = rep(0:10, rep(100, 11)), 
                 .id = as.integer(rep(seq(1, 100, 1), 11)), 
                 site = rep(sample(1:6, size = 100, replace = TRUE), 11), 
                 x1 = rep(rnorm(100, mean = 1, sd = 0.5), 11))
# Create NA
df[sample(1:100, size = 50, replace = FALSE), 'x1'] <- NA
# impute
mids <- as.mids(df, .imp = 1)

# Standardize before analysis
mids %>% 
  complete(action = "all") %>% 
  map(~ mutate(., x1_stan = x1 - tapply(x1, site, mean)[site])) %>% 
  map(lm, formula = x1_stan ~ as.factor(site)) %>% 
  pool()
#> Class: mipo    m = 10 
#>               term  m      estimate       ubar b          t dfcom       df riv
#> 1      (Intercept) 10  3.867247e-16 0.01337123 0 0.01337123    94 92.05264   0
#> 2 as.factor(site)2 10 -3.081936e-16 0.03030813 0 0.03030813    94 92.05264   0
#> 3 as.factor(site)3 10 -3.239129e-16 0.02748531 0 0.02748531    94 92.05264   0
#> 4 as.factor(site)4 10 -4.019890e-16 0.03646700 0 0.03646700    94 92.05264   0
#> 5 as.factor(site)5 10 -4.963935e-16 0.02924958 0 0.02924958    94 92.05264   0
#> 6 as.factor(site)6 10 -6.327414e-16 0.02546902 0 0.02546902    94 92.05264   0
#>   lambda        fmi
#> 1      0 0.02104097
#> 2      0 0.02104097
#> 3      0 0.02104097
#> 4      0 0.02104097
#> 5      0 0.02104097
#> 6      0 0.02104097
```

<sup>Created on 2021-03-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by gerkovink** [comment] 2021-03-27 09:40
Closing as the behaviour by `as.mids()` is as expected

**Closed by gerkovink** 2021-03-27 09:40 UTC

**Comment by mragusi** [comment] 2021-03-27 09:44
Hi Gerko,

Thanks for your swift answer. Ok, it makes sense that values that are observed shouldn't be different across imputations. I will use your mentioned approach.

Enjoy your weekend!
